config/routes.rb
Rails.application.routes.draw do
  get 'bookings/index'
  get 'hotels/index'
  get 'users/index'
  get 'users/profile'
  get 'hotels/search'
  root 'top#index'
  post 'hotels/booking_confirm'
  post 'hotels/back'
  post 'hotels/booking_complete'



  #get 'signup', to: 'users#new'


  devise_for :users
  resources :users, only: [:index, :show, :update]
  resources :hotels
  resources :bookings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord


    belongs_to :hotel
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  with_options on: :create do
  validates :hotel_name, presence: true, length: { maximum: 30 }
  validates :hotel_introduction, presence: true
  validates :hotel_price, presence: true, numericality: { only_integer: true }
  validates :hotel_address, presence: true
  validates :user_id, presence: true, numericality: { only_integer: true }
  validate :hotel_image_type, :hotel_image_size
  end

  with_options on: :booking_confirm do
  validate :not_before_day
  validate :is_after_day
  validates :hotel_id, presence: true, numericality: { only_integer: true }
  validates :client_num, presence: true, numericality: { only_integer: true }
  end

  with_options on: :booking_complete do
  validate :not_before_day
  validate :is_after_day
  validates :total_price, presence: true, numericality: { only_integer: true }
  validates :hotel_id, presence: true, numericality: { only_integer: true }
  validates :client_num, presence: true, numericality: { only_integer: true }
  validates :using_days, presence: true, numericality: { only_integer: true }
  end


  has_one_attached :hotel_image


  belongs_to :user
  has_many :bookings




  private
  
  def hotel_image_type
    if (hotel_image.attached?)
      if !hotel_image.blob.content_type.in?(%('hotel_image/jpeg hotel_image/png'))
        hotel_image.purge
        errors.add(:hotel_image, "はjpegまたはpng形式でアップロードしてください")
      end
    else
      errors.add(:hotel_image, "画像をアップロードしてください")
    end
  end

  def hotel_image_size
    if hotel_image.attached?
      if hotel_image.blob.byte_size > 5.megabytes
        hotel_image.purge
        errors.add(:hotel_image, "は1つのファイル5MB以内にしてください")
      end
    end
  end

  def not_before_day
    errors.add(:check_in, 'は明日以降の日付を入力して下さい') if check_in.nil? || check_in >= Date.today
  end

  def is_after_day
    errors.add(:check_in, 'は終了日以降の日付を入力して下さい') if check_in.nil? || check_in <= check_out
  end



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 30 }

  #with_options on: :update do
  #validates :introduction, presence: true, length: { maximum: 100 }
  #end

  has_one_attached :avatar
  has_many :hotels
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :set_search

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:avatar] )
    end

    def set_search
        @q = Hotel.ransack(params[:q])
        @results = @q.result
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  protect_from_forgery
  def index
    @bookings = Booking.all
  end

  def new
  end

  def create

  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    flash[:notice] = "予約を削除しました"
    redirect_to :bookings
  end
  

end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController

  protect_from_forgery


  def index
    @hotels = Hotel.all
  end

  def new
    @hotel = Hotel.new
    @user = current_user
  end

  def create
    @hotel = Hotel.new(hotel_params)
    if @hotel.valid?(:create) && @hotel.save
      flash[:notice] = "ルームを新規登録しました"
      redirect_to:hotels
    else
      @user = current_user
      flash[:alert] = "登録できませんでした。"
      render :new
    end
  end

  def show
    @hotel = Hotel.find(params[:id])
    @booking = Booking.new
  end

  def edit
  end

  def update
  end

  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy
    flash[:notice] = "ルームを削除しました"
    redirect_to :hotels
  end

  def booking_confirm
    @booking = Booking.new(booking_confirm_params)
    @hotel = Hotel.find(@booking.hotel_id)
    if @booking.valid?(:booking_confirm) 
      @booking.using_days = @booking.check_out - @booking.check_in
      @booking.total_price = @hotel.hotel_price * @booking.client_num * @booking.using_days
    else
      flash[:alert] = "まだ予約は完了しておりません。"
      render :show
    end
  end

  def booking_complete
    @booking = Booking.new(booking_params)
    if @booking.valid?(:booking_complete) && @booking.save
      flash[:notice] = "ルームを予約しました"
      redirect_to:bookings
    else
      @hotel = Hotel.find(@booking.hotel_id)
      flash[:alert] = "予約できませんでした。"
      render :new
    end
  end

  private

  def hotel_params
    params.require(:hotel).permit(:hotel_image, :hotel_name, :hotel_introduction, :hotel_price, :hotel_address, :user_id)
  end

	def booking_confirm_params
    params.require(:booking).permit(:check_in, :check_out, :hotel_id, :client_num)
	end

  def booking_params
    params.require(:booking).permit(:total_price, :check_in, :check_out, :hotel_id, :client_num, :using_days)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

    def index
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #before_action :authenticate_user!, except: [:index]

  def index
    @users = User.all
  end

  def show
    @user = current_user
  end

  def profile
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(params.require(:user).permit(:name, :introduction, :avatar))
      flash[:notice] = "#{@user.name}さんのユーザー情報を更新しました"
      redirect_to(users_profile_path(current_user.id))
    else
      flash[:alert] = "更新できませんでした。"
      render "profile"
    end
  end
  
  
=begin
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "ユーザーを新規登録しました"
      redirect_to("/")
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirm)
    end
=end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/index.html.erb
<h1>予約済みルーム一覧</h1>

<% if flash.notice %>
    <p class="notice"><%= flash.notice %></p>
<% end %>

<table>
    <thead>
        <tr>
            <!--<th>id</th>-->
            <th>ルーム画像</th>
            <th>ルーム名</th>
            <th>ルーム紹介</th>
            <th>合計料金</th>
            <th>開始日</th>
            <th>終了日</th>
            <th>予約確定日時</th>
            <!--<th>物件id</th>-->
            <th>人数</th>
            <th>使用日数</th>
            <th>削除</th>
        </tr>
    </thead>

    <tbody>
        <% @bookings.each do |booking| %>
            <tr>
                <!--<td><%= booking.id %></td>-->
                <td><%= image_tag booking.hotel.hotel_image, size: '200x200' %></td>
                <td><%= booking.hotel.hotel_name %></td>
                <td><%= booking.hotel.hotel_introduction %></td>
                <td>¥<%= booking.total_price %></td>
                <td><%= booking.check_in %></td>
                <td><%= booking.check_out %></td>
                <td><%= l booking.created_at %></td>
                <!--<td><%= booking.hotel_id %></td>-->
                <td><%= booking.client_num %>人</td>
                <td><%= booking.using_days %>日</td>
                <td>
                    <%= link_to "削除", booking, method: :delete, data: { confirm: "本当に削除しますか？" } %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/hotels/booking_confirm.html.erb
  <h1>予約確認画面</h1>
 
    <table>
      <tr>
        <th>開始日</th>
        <td><%= @booking.check_in %></td>
      </tr>
      <tr>
        <th>終了日</th>
        <td><%= @booking.check_out %></td>
      </tr>
      <tr>
        <th>使用日数</th>
        <td><%= @booking.using_days %>日</td>
      </tr>
      <tr>
      <tr>
        <th>人数</th>
        <td><%= @booking.client_num %>人</td>
      </tr>
        <th>金額(お一人様あたり)</th>
        <td>¥<%= @hotel.hotel_price %></td>
      </tr>
      <tr>
        <th>合計金額</th>
        <td>¥<%= @booking.total_price %></td>
      </tr>
    </table>

    <%= form_for @booking, method: :confirm, url: hotels_booking_complete_path do |f| %>

        <%= f.hidden_field :total_price, value: @booking.total_price %>    

        <%= f.hidden_field :check_in, value: @booking.check_in %>
    
        <%= f.hidden_field :check_out, value: @booking.check_out %>    

        <%= f.hidden_field :hotel_id, value: @booking.hotel_id %>

        <%= f.hidden_field :client_num, value: @booking.client_num %>
        
        <%= f.hidden_field :using_days, value: @booking.using_days %>

        <%= f.submit '上記で予約する', class: 'btn btn-primary btn-block' %>
    <% end %>
    <p><%= link_to "TOPへ戻る", root_path %></p>

app/views/hotels/index.html.erb
<h1>ルーム情報一覧</h1>

<% if flash.notice %>
    <p class="notice"><%= flash.notice %></p>
<% end %>



<table>
    <thead>
        <tr>
            <!--<th>id</th>-->
            <th>ルーム画像</th>
            <th>ルーム名</th>
            <th>ルーム紹介</th>
            <th>料金</th>
            <th>住所</th>
            <th>登録日</th>
            <th>削除</th>
        </tr>
    </thead>

    <tbody>

        <% @hotels.each do |hotel| %>
            <tr>
                <!--<td><%= hotel.id %></td>-->
                <td><%= image_tag hotel.hotel_image, size: '200x200' %></td>
                <td><%= link_to hotel.hotel_name, hotel %></td>
                <td><%= hotel.hotel_introduction %></td>
                <td><%= hotel.hotel_price %></td>
                <td><%= hotel.hotel_address %></td>
                <td><%= l hotel.created_at %></td>
                <td>
                    <%= link_to "削除", hotel, method: :delete, data: { confirm: "本当に削除しますか？" } %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

<p><%= link_to "ルーム登録（debug用）", new_hotel_path %></p>

app/views/hotels/new.html.erb
<% if user_signed_in? %>
    <h1>ルーム情報登録</h1>

    <% if flash.notice %>
        <p class="alert"><%= flash.alert %></p>
    <% end %>

    <%= render "shared/error", obj: @hotel %>

    <%= form_for @hotel do |f| %>

        <div class="field">
            <%= f.label :hotel_image ,"ルーム画像" %>
            <%= f.file_field :hotel_image %>
        </div>

        <div class="form-group">
            <%= f.label :hotel_name, 'ルーム名' %>
            <%= f.text_field :hotel_name, class: 'form-control' %>
        </div>
    
        <div class="form-group">
            <%= f.label :hotel_introduction, 'ルーム紹介' %>
            <%= f.text_field :hotel_introduction, class: 'form-control' %>
        </div>
    
        <div class="form-group">
            <%= f.label :hotel_price, '料金' %>
            <%= f.number_field :hotel_price, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :hotel_address, '住所' %>
            <%= f.text_field :hotel_address, class: 'form-control' %>
        </div>
        

        <%= f.hidden_field :user_id, value: @user.id %>

        <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>

    <p><%= link_to "TOPへ戻る", root_path %></p>
<% else %>
    <h1>ログインしてください</h1>
    <p><%= link_to "TOPへ戻る", root_path %></p>
<% end %>

app/views/hotels/search.html.erb
<table>
    <thead>
        <tr>
            <th>id</th>
            <th>ルーム画像</th>
            <th>ルーム名</th>
            <th>ルーム紹介</th>
            <th>料金</th>
            <th>住所</th>
            <th>作成日</th>
            <th>ルーム予約</th>
            <th>参照</th>
            <th>削除</th>
        </tr>
    </thead>

    <tbody>

        <% @results.each do |result| %>
            <tr>
                <td><%= result.id %></td>
                <td><＃%= image_tag hotel.hotel_image, size: '200x200' %></td>
                <td><%= result.hotel_name %></td>
                <td><%= result.hotel_introduction %></td>
                <td><%= result.hotel_price %></td>
                <td><%= result.hotel_address %></td>
                <td><%= result.created_at %></td>

                <td>
                    <%= link_to "予約する", new_booking_path(result.id) %>
                </td>
                <td>
                    <%= link_to "参照", hotel_path(result.id) %>
                </td>
                <td>
                    <%= link_to "削除", hotel_path(result.id), method: :delete, data: { confirm: "本当に削除しますか？" } %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/hotels/show.html.erb
<% if user_signed_in? %>
    <h1>ルーム予約</h1>

    <% if flash.notice %>
        <p class="alert"><%= flash.alert %></p>
    <% end %>

    <%= render "shared/error", obj: @booking %>

    <%= form_for @booking, method: :confirm, url: hotels_booking_confirm_path do |f| %>

    
        <div class="form-group">
            <%= f.label :check_in, '開始日' %>
            <%= f.date_field :check_in, class: 'form-control' %>
        </div>
    
        <div class="form-group">
            <%= f.label :check_out, '終了日' %>
            <%= f.date_field :check_out, class: 'form-control' %>
        </div>      

        <div class="form-group">
            <%= f.label :client_num, '人数' %>
            <%= f.number_field :client_num, class: 'form-control' %>
        </div> 
        
        <%= f.hidden_field :hotel_id, value: @hotel.id %>


        <%= f.submit '予約確認画面へ', class: 'btn btn-primary btn-block' %>
    <% end %>

    <p><%= link_to "TOPへ戻る", root_path %></p>
<% else %>
    <h1>ログインしてください</h1>
    <p><%= link_to "TOPへ戻る", root_path %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelReservation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <div class = header-left>
    <%= search_form_for @q, url: hotels_search_path do |f| %>
      <%= f.label :hotel_address_cont, 'エリア検索' %>
      <%= f.search_field :hotel_address_cont,class:'search',placeholder: 'エリア' %>
      <%= f.label :hotel_name_or_hotel_address_cont, 'キーワード検索' %>
      <%= f.search_field :hotel_name_or_hotel_address_cont,class:'search',placeholder: 'キーワード' %>
      <%= f.submit "検索" %>
    <% end %>
  </div>
  -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.
  <p><%= link_to "TOP画面", root_path %></p>
  <!--<p><%= link_to "ユーザー一覧（debug用）", users_path %></p>-->
  <p><%= link_to "ルーム登録", new_hotel_path %></p>
  <p><%= link_to "予約済みルーム一覧", bookings_path %></p>
  <p><%= link_to "登録済みルーム一覧", hotels_path %></p>
  -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.
  <% if user_signed_in? %>
    <h2> 現在 <%= current_user.name %> さんがログインしています </h2>
    <h4> メールアドレス： <%= current_user.email %> </h4>
    <p><%= link_to "アカウント", user_path(current_user.id) %></p>
    <p><%= link_to "マイページ", users_profile_path(current_user.id) %></p>
    <p><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></p>

  <% else %>
    <h2> 現在ログインしていません </h2>
      <%= link_to "ログイン", new_user_session_path, class: 'post' %>
      <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
  <% end %>
  </header>
    <%= yield %>
  </body>
</html>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
    <% obj.errors.full_messages.each do |message| %>
        <ul>
            <li><%= message %></p>
        </ul>
    <% end %>
<% end %>

app/views/top/index.html.erb
<div>
<p>Potepan Shareでまだ体験したことのない旅をしよう</p>

</div>

app/views/users/edit.html.erb
<h3>ユーザー編集</h3>
 
    <%= form_for @user do |f| %>
      <table>
        <tr>
          <th><%= f.label :name ,"名前" %></th>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <th><%= f.label :email ,"メールアドレス" %></th>
          <td><%= f.text_field :email %></td>
        </tr>
        <tr>
          <th><%= f.label :introduction ,"自己紹介" %></th>
          <td><%= f.text_area :introduction %></td>
        </tr>
      </table>
      <div>
        <ul>
          <li><%= f.submit "編集を完了する" %></li>
          <li><%= link_to "ユーザー情報一覧に戻る", :users %></li>
        </ul>
      </div>
    <% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>


<h1>ユーザー情報一覧（debug用）</h1>

<% if flash.notice %>
    <p class="notice"><%= flash.notice %></p>
<% end %>

<table>
    <thead>
        <tr>
            <th>id</th>
            <th>名前</th>
            <th>メールアドレス</th>
            <th>自己紹介</th>
            <th>更新日</th>
            <th>作成日</th>
            <th>参照</th>
            <th>編集</th>
        </tr>
    </thead>

    <tbody>
        <% @users.each do |user| %>
            <tr>
                <td><%= user.id %></td>
                <td><%= user.name %></td>
                <td><%= user.email %></td>
                <td><%= user.introduction %></td>
                <td><%= user.updated_at %></td>
                <td><%= user.created_at %></td>
                <td>
                    <%= link_to "参照", user %>
                </td>
                <td>
                    <#%= link_to "編集", [:edit, user] %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/users/profile.html.erb
<% if flash.notice %>
    <p class="notice"><%= flash.notice %></p>
    <% elsif flash.alert%>
    <p class="alert"><%= flash.alert %></p>
<% end %>

<h3>プロフィール</h3>

<%= render "shared/error", obj: @user %>

<%= form_for @user do |f| %>
  <% if @user.avatar.attached? %>
    <%= image_tag @user.avatar, size: '200x200' %>
  <% else %>
    <%= image_tag 'default_icon.jpeg', size: '200x200' %>
  <% end %>

  <div class="field">
    <%= f.label :avatar ,"アイコン画像" %>
    <%= f.file_field :avatar %>
  </div>
      <table>
        <tr>
          <th><%= f.label :name ,"名前" %></th>
          <td><%= f.text_field :name %></td>
        </tr>

        <tr>
          <th><%= f.label :introduction ,"自己紹介" %></th>
          <td><%= f.text_area :introduction %></td>
        </tr>
      </table>


      <div>
        <ul>
          <li><%= f.submit "編集を完了する" %></li>
        </ul>
      </div>
    <% end %>

app/views/users/show.html.erb
<h3>アカウント</h3>
<table>
  <tr>
    <th>メールアドレス</th>
    <td><%= @user.email %></td>
  </tr>
</table>

<div>
  <ul>
    <li><%= link_to "編集", edit_user_registration_path %></li>
  </ul>
</div>